server:
  port: 3344
spring:
  application:
    name: cloud-config-center
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/asiariven/springcloud-config.git0
          username: 1014465379@qq.com
          password: yazhou231
          search-paths:
            - springcloud-config
          label: master
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
eureka:0
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
management:
  endpoints:
    web:
      exposure:
        include: 'bus-refresh'